name: 'Empty Changelog Check'
description: 'Check for empty changelog entries in pull requests'
author: 'your-username'

inputs:
  github-token:
    description: 'GitHub token for API operations'
    required: true
    default: ${{ github.token }}
  label-name:
    description: 'Label to add when empty changelog is detected'
    required: false
    default: 'empty-changelog'

outputs:
  has_empty_changelog:
    description: 'Whether empty changelog entries were found'
  empty_headers:
    description: 'List of empty changelog headers'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'alert-circle'
  color: 'yellow'
